### ISSUE TITLE
Dehydrating stores with routr

### ISSUE THREAD

**Issue by gpbl** [yahoo/fluxible-app#23]
I'm new to fluxible and I'm trying to setup my first app with it, so I apologize in advance for the silly question.

I configured my routes to execute an action, which should load an array of photos before rendering the home page:

```js
// routes.js
var getPhotos = require('../actions/getPhotos');
var routes = {
  home: {
    path: '/', method: 'get', page: 'home', label: 'Home',
    action: function(context, payload, done) {
      // will add an array of photos to the PhotosStore
      context.executeAction(getPhotos, {}, done);
    }
}
```
On the server I'm dehydrating data as in the examples:
```js
var context = app.createContext();
var actionContext = context.getActionContext();
actionContext.executeAction(navigateAction, { url: req.url },function (err) {
    var state = 'window.App=' + serialize(app.dehydrate(context), 'App'); // etc
```

Now the dehydrated state does not contain the PhotosStore, only the ApplicationStore. The component, rendered server-side, loads the photos regularly. 

Clearly I'm missing some base concept: how to dehydrate the other stores as well?

**Comment by gpbl** [comment]
Got it, I was using `this.emit('change')` instead of `this.emitChange()` in my PhotosStore. Is then [this example](https://github.com/yahoo/flux-examples/blob/master/routing/stores/TimeStore.js#L16) wrong?

**Comment by redonkulus** [comment]
@gpbl you are correct, that must have been missed when we refactored. I've updated the example. Thanks!
